set_languages("cxx20")
set_arch("x64")
add_rules("mode.debug", "mode.release")
add_requires("spdlog 1.10.*", "nlohmann_json 3.11.*")

target("skip_main_menu")
    set_kind("shared")
    set_filename("cp_skip_main_menu.asi")
    add_packages("spdlog", "nlohmann_json")
    add_defines("UNICODE", "WIN32_LEAN_AND_MEAN")
    set_pcxxheader("src/pch.h")
    add_files("src/**.cpp")
    add_links("User32")
    add_headerfiles("src/**.h")
    add_includedirs("src/")
    on_install(function(target)
        cprint("${green bright}Installing..")
        assert(os.isdir("$(installpath)"), format("The path in your configuration doesn't exist or isn't a directory.\n\tUse the follow command to set install path:\n\txmake f --installpath=%s", [["C:\Program Files (x86)\Steam\steamapps\common\Cyberpunk 2077\bin\x64\plugins"]]))
        os.cp(target:targetfile(), "$(installpath)")
        cprint("Installed at: ${underline}%s", "$(installpath)")
    end)
    on_package(function (target) 
        os.rm("package/*")
        os.mkdir("package/bin/x64/plugins/cyber_engine_tweaks/mods/cp_skip_main_menu/archive")
        os.cp("scripts/*", "package/bin/x64/plugins/cyber_engine_tweaks/mods/cp_skip_main_menu")
        os.cp("archive/*", "package/bin/x64/plugins/cyber_engine_tweaks/mods/cp_skip_main_menu/archive")
        os.cp("LICENSE", "package/bin/x64/plugins/cyber_engine_tweaks/mods/cp_skip_main_menu")
        os.cp(target:targetfile(), "package/bin/x64/plugins/")
    end)


option("installpath")
    set_default("installpath")
    set_showmenu(true)
    set_description("Set the path to install the asi to.", "e.g.", format("\t-xmake f --installpath=%s", [["C:\Program Files (x86)\Steam\steamapps\common\Cyberpunk 2077\bin\x64\plugins"]]))